env:
  browser: true
  es2021: true
extends:
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {}
